### ISSUE TITLE
run :: handle_wifi :: 1 :: error :: "wpa_cli" unexpectedly returned exit value 255 at /usr/bin/occi line 298.

### ISSUE THREAD

**Issue by fdattein** [adafruit/Adafruit-Occi#6]
Hi there,

I am running HypriotOS 1.1.3 on a RPI 3 and I am having the following error, when I run `sudo occi`. :
```
root@black-pearl:/home/pirate# sudo occi
Adafruit Occidentalis configuration helper, v0.6.0
file :: /boot/occidentalis.txt
run :: handle_selftest :: Checking configuration for basic sanity.
run :: handle_selftest :: valid :: hostname :: black-pearl
run :: handle_selftest :: valid :: wifi_password :: xxxxxxxxx
run :: handle_selftest :: valid :: wifi_ssid :: brazil
run :: handle_selftest :: have package :: occi
run :: handle_selftest :: have package :: occidentalis
run :: handle_selftest :: debian version :: 8.0
run :: handle_wifi :: Configuring network :: brazil
run :: handle_wifi :: Writing /etc/wpa_supplicant/wpa_supplicant.conf
Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory
run :: handle_wifi :: 1 :: error :: "wpa_cli" unexpectedly returned exit value 255 at /usr/bin/occi line 298.
```

````
root@black-pearl:/home/pirate# cat /boot/occidentalis.txt
hostname=black-pearl

# basic wireless networking options:
wifi_ssid=brazil
wifi_password=xxxxxxx
````

**Comment by brennen** [comment]
I'm afraid this is the first I've heard of HypriotOS.  It sounds like it's Debian-based, but I'm not sure what its point of departure is.  `occi` is fairly tightly coupled to a stock Raspbian Jessie install; I would not be surprised if this breaks on a newer upstream.  Probably need to test it against a Stretch-derived version.

**Comment by fdattein** [comment]
HypriotOS was Raspbian based and I read something about them moving to Debian. That must be the cause of this issue.

**Comment by StefanScherer** [comment]
@fsamir HypriotOS is still Raspbian based. But [since 1.0.0](https://github.com/hypriot/image-builder-rpi/releases/tag/v1.0.0) we have switch from occi to [device-init](https://github.com/hypriot/device-init).

**Comment by brennen** [comment]
Interesting. @fsamir, just out of curiosity, can I confirm that you were using occi as a baseline config tool for a while there?  First I've really heard of your project.

Sounds like this specific issue can likely be closed, but we might want to look at a refresh on this stuff soon.

**Comment by fdattein** [comment]
@StefanScherer thanks for the heads up. I will have a look at device-init.

@brennen it is the opposite. It was the first time I tried occi on hypriotOS and it didn't work from the beginning. I assumed it would work because there is a blog post on Hypriot's web-site, which is clear now that is outdated.

Feel free to close this issue. Thanks!

**Comment by brennen** [comment]
Sure thing.  Best of luck. :)

**Comment by julianfrank** [comment]
```
Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory
run :: handle_wifi :: 1 :: error :: "wpa_cli" unexpectedly returned exit value 255 at /usr/bin/occi line 298.
```
I'm getting the same error on RPi3 and device-init is of no use either :( ... sadly device-init there is no way to know why it is not working either...
